console.log(">>>>>>>>>>>> Inicio do JS")

//loadScript("cc_inst_contract.js")

var caduABI = [{"constant":false,"inputs":[{"name":"_autorizado","type":"address"},{"name":"_bloco","type":"uint8"}],"name":"bloqueio_bloco","outputs":[],"type":"function"},{"constant":false,"inputs":[{"name":"_autorizado","type":"address"},{"name":"_bloco","type":"uint8"}],"name":"liberacao_bloco","outputs":[],"type":"function"},{"constant":true,"inputs":[{"name":"","type":"uint256"}],"name":"permissoes","outputs":[{"name":"pessoa","type":"address"},{"name":"autorizado","type":"address"},{"name":"bloco","type":"uint8"}],"type":"function"},{"constant":false,"inputs":[{"name":"_nome","type":"bytes32"},{"name":"_dia_nasc","type":"uint8"},{"name":"_mes_nasc","type":"uint8"},{"name":"_ano_nasc","type":"uint8"}],"name":"cadastro_alteracao_bloco1","outputs":[],"type":"function"},{"constant":true,"inputs":[],"name":"contador_permissao","outputs":[{"name":"","type":"uint256"}],"type":"function"},{"constant":true,"inputs":[{"name":"_pessoa","type":"address"}],"name":"consulta_gerais","outputs":[{"name":"nome","type":"bytes32"},{"name":"dia_nasc","type":"uint8"},{"name":"mes_nasc","type":"uint8"},{"name":"ano_nasc","type":"uint8"}],"type":"function"},{"inputs":[],"type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"name":"descricao","type":"string"},{"indexed":false,"name":"success","type":"bool"},{"indexed":false,"name":"nome","type":"bytes32"},{"indexed":false,"name":"dia_nasc","type":"uint8"},{"indexed":false,"name":"mes_nasc","type":"uint8"},{"indexed":false,"name":"ano_nascimento","type":"uint8"},{"indexed":false,"name":"mensagem","type":"string"}],"name":"ReturnCadBloco1","type":"event"},{"anonymous":false,"inputs":[{"indexed":false,"name":"descricao","type":"string"},{"indexed":false,"name":"success","type":"bool"},{"indexed":false,"name":"pessoa","type":"address"},{"indexed":false,"name":"bloco","type":"uint8"},{"indexed":false,"name":"qtde_blocos","type":"uint8"},{"indexed":false,"name":"mensagem","type":"string"}],"name":"ReturnPermissao","type":"event"}];

var cadu = eth.contract(caduABI).at("0xca0520024f55084b4f74cfc7f7aa71e887b21596");


console.log(">>>>>>>>>>>> Fim do JS ^^^^^^^^^^^^^^^^^^^^^^^^^^^")